<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>sleder title generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="sleder title, WOW Slider, jquery gallery, bootstrap carousel" />
	<meta name="description" content="sleder title created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="{{Asset('public/assets/engine1/style.css')}}" />
	<script type="text/javascript" src="{{Asset('public/assets/engine1/jquery.js')}}"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#d7d7d7">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><a href="#" target="target"><img src="{{Asset('public/assets/data1/images/slide1.jpg')}}" alt="slide-1" title="slide-1" id="wows1_0"/></a>Mo ta 1</li>
<li><a href="#" target="d"><img src="{{Asset('public/assets/data1/images/slide2.jpg')}}" alt="slide-2" title="slide-2" id="wows1_1"/></a>mo ta 2</li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="slide-1">1</a>
<a href="#" title="slide-2">2</a>
</div></div>
<span class="wsl"><a href="http://wowslider.net">jquery image slider</a> by WOWSlider.com v5.5</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="{{Asset('public/assets/engine1/wowslider.js')}}"></script>
	<script type="text/javascript" src="{{Asset('public/assets/engine1/script.js')}}"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>